const categories = Object.freeze([
    "Drawing and Painting",
    "Photography",
    "Writing",
    "Reading",
    "Cooking",
    "Gardening",
    "Knitting and Crocheting",
    "Woodworking",
    "Sculpting",
    "Playing Musical Instruments",
    "Dancing",
    "Hiking",
    "Camping",
    "Fishing",
    "Bird Watching",
    "Yoga and Meditation",
    "Fitness and Exercise",
    "Running",
    "Cycling",
    "Swimming",
    "Singing",
    "Acting and Theater",
    "DIY and Crafts",
    "Collecting (Stamps, Coins, etc.)",
    "Gaming",
    "Traveling",
    "Chess and Board Games",
    "Model Building",
    "Metalworking",
    "Fashion Design"
  ]);

  export default categories;